### ISSUE TITLE
Additional Resources

### ISSUE THREAD

**Issue by nvengal** [midohiofoodbank/freshtrak-pantry-finder-api#6]

**Comment by davidpickering** [comment]
Food Bank Story: I am a food bank and I want to publish my list of agencies on FreshTrak.com, however I am not currently able to provide enough information to allow listings of specific dates of service. I would like all of my agencies to initially display in the "Additional Resources" section.

From a data perspective, the only difference between the "Resource Events" and "Additional Resources" should be the events.status_publish_event_dates == 0 (for Additional Resources) instead of events.status_publish_event_dates == 1 (for resource events). This is regardless of the presence of data in the event_dates table.

Open Question: How do we handle the request and pass the data back?
- Proposal - Request - Feed in a parameter along the lines of "include_additional_resources=TRUE"
- Proposal - Response - Place the additional_resources agencies into the same "agencies" object, 
- Proposal - Response - also include some derivative of the  events.status_publish_event_dates so users of the API can separate the data if they need to (our use case) or use it all together (theoretical use case for providing a single list).

@nvengal & @PhilNorman2 seem like a solid option?

**Comment by PhilNorman2** [comment]
Question: Will Events be included in this view?

**Comment by nvengal** [comment]
> Question: Will Events be included in this view?
I would not expect events to be included since these agencies explicitly don't want us to publish events.

> As far as the API design goes it might be better to do a separate API call using the param.
Agreed. A separate api call will be simpler. As far as how that's implemented, I think we can leave the question open until someone starts work on this and then iterate on the exact approach in the pull request.

**Comment by davidpickering** [comment]
> 
> 
> >    Question: Will Events be included in this view?

> I would not expect events to be included since these agencies explicitly don't want us to publish events.

Yes, we will publish the agencies (locations) and events (events), but not the event_dates (specific dates).

Agreed. A 

> separate api call will be simpler. As far as how that's implemented, I think we can leave the question open until someone starts work on this and then iterate on the exact approach in the pull request.

Okay, so process-wise we are thinking it is  2nd API call. Do we want it to be a call to the same endpoint with a different parameter? Or a new endpoing?

**Comment by PhilNorman2** [comment]
I think I agree with Nikhil that is a design decision that can be delayed
until someone starts working on it.  Is there a reason for the urgency?

**Comment by davidpickering** [comment]
Haha, no particular new urgency besides everything that has been going on for the past 40 days. Just trying to get stuff out there and described well enough to get worked on. You all are great, keep up the good work!

**Comment by PhilNorman2** [comment]
Wow, 40 days.  Seems longer and shorter at the same time.

**Comment by davidpickering** [comment]
We've mostly abandoned this concept. It still holds validity, but there hasn't been interest on the implementation side.
