### ISSUE TITLE
Filter events by service category

### ISSUE THREAD

**Issue by nvengal** [midohiofoodbank/freshtrak-pantry-finder-api#7]

**Comment by PhilNorman2** [comment]
@davidpickering I started working on this.  So far I am able to limit by service_category at the agency level but not at the event level.  For example if I limit by service_category = 20 ("Produce") it retrieves agencies that have at least one event with the service category of "Produce".  However, for agencies that have more than one event it will include events that have other service categories such as "Prepack Pantry" or "Choice Pantry".   Is that acceptable?

**Comment by PhilNorman2** [comment]
Here is what the SQL query generated from by the current Agency model method looks like:

SELECT DISTINCT `locations`.* 
FROM `locations` 
INNER JOIN `events` ON `events`.`status_id` = 1 
AND `events`.`status_publish_event` = 1 
AND `events`.`loc_id` = `locations`.`loc_id` 
INNER JOIN `service_types` ON `service_types`.`service_id` = `events`.`service_id` 
WHERE `locations`.`status_id` = 1 AND (service_types.service_category1 = '20')

**Comment by davidpickering** [comment]
Hey @PhilNorman2 yes, that SQL is legit. I'm guessing the 'issue' is that the agencies serialize-er is getting the filtered list of agencies, then also getting all events for those agencies slightly expanding the scope of returned data? 

One one hand I'd go for 90% filtered with a little chatter in there. However, I'm thinking since this is a user filter option we want really solid behavior (never showing an event that didn't provide the selected service category). Sorry, looks like we should keep working on this one!

**Comment by PhilNorman2** [comment]
I understand.  You could be right about the serializer but I don't know of a safe way to blow away a serializer object in real time without causing an exception.  Not sure what we can do here at the moment.  I just tried moving the scope to the event and that returned the correct events but did not include the agency information.

**Comment by davidpickering** [comment]
Not a bad idea, but closing in favor of the detail available on the logged-in landing page.
