### ISSUE TITLE
Filter events by date

### ISSUE THREAD

**Issue by nvengal** [midohiofoodbank/freshtrak-pantry-finder-api#8]

**Comment by davidpickering** [comment]
@PhilNorman2 what had been our last thinking on filtering the agencies API call by date? Built in, the agencies API uses a date parameter to filter the event dates >= [date]?
https://pantry-finder-api.beta.freshtrak.com/api/agencies?zip_code=43123

So, what is a good way we can build some date filtering controls into this process? Should these be 
- front_end->api_call->filtering->return (in API)->display?
- or -  front_end->api_call->return ->filtering(in client)->display?

Also, if we don't like any of these ideas, I have a prototype design we could consider reformatting search results in line with:

Or... most of this feedback is from foodbank users. So, there is some validity to it, but since we don't have a lot of usage by customers of the search tool we don't have much feedback from them.

**Comment by PhilNorman2** [comment]
I think this ties into our discussion today.  The current event_date param in the agencies API shows using the agencies end point responds with agencies whose events have at least one event_date that matches the criteria, it is the same issue as the "service".   And event if we move everything to the event end point, we will have the same issue with event_date as it is one level down from events.  I will be sure we include event_date limiting in our discussion as well.

**Comment by davidpickering** [comment]
Closed in favor of logged-in landing page. The logged in landing page presents the information in different timeframes.
![image](https://user-images.githubusercontent.com/11682225/94638334-b8e8f180-02a7-11eb-9519-e0fc37a247e8.png)
